---
title: "Gráficos correspondencias múltiples"
output: html_notebook
---

Levantar la tabla parcial que contiene solo las variables categóricas (8 ocho) (30/11/2017)
```{r}
unlp_ris_rg <- read.csv2("Presencia_investigadores_UNLP_en_RG_y_RIS.csv", header = TRUE, na.strings = "NA")
```

Convertir el data.frame en tipo tibble
```{r}
library(tidyverse)
unlp_ris_rg <- as_tibble(unlp_ris_rg) #cambió a tibble..
```

Veo de generar el grafico MCA usando FactoMineR. 
```{r}
library(FactoMineR)
library(ggplot2)
library(factoextra)
```

Selecciono las variables que entrarán - ocho categoricas
```{r}
# Selecciono las variables que entrarán - siete
unlp_ris_rg.active <- unlp_ris_rg[2:705, c("Categoria", "Facultad", "Sexo", "ResearchGate", "SEDICI", "Memoria", "Naturalis")]
head(unlp_ris_rg.active[, c("Categoria", "Facultad", "Sexo", "ResearchGate", "SEDICI", "Memoria", "Naturalis")], 706)
summary(unlp_ris_rg.active)
res.mca <- MCA(unlp_ris_rg.active, ncp = 2, ind.sup = NULL, quanti.sup = NULL, 
               quali.sup = NULL, excl=NULL, graph = TRUE, 
               axes = c(1,2), method="Indicator", na.method="NA")
```

# fviz_mca_biplot(res.mca, repel = TRUE, ggtheme = theme_minimal())
